name: WB Stocks to Supabase

on:
  schedule:
    - cron: "*/30 * * * *"  # каждые 30 минут
  workflow_dispatch: {}      # запуск вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run incremental sync (last 31 minutes)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          WB_API_KEY: ${{ secrets.WB_API_KEY }}
          FULL_SYNC: "0"
        run: |
          python stocks_sync.py
